services:
  vertex-block:
    build: .
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./blocklists:/app/blocklists:ro
      - ./src:/app/src:ro

  docs:
    image: squidfunk/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - .:/docs:ro
    command: serve -a 0.0.0.0:8000
